<?php
use Drupal\noahs_page_builder\Controls_Base;
use Drupal\noahs_page_builder_pro\noahs_page_builderProController;

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\FieldDefinition;
use Drupal\Core\Field\BaseFieldDefinition;

// define( 'NOAHS_PAGE_BUILDER_PATH',  \Drupal::service('extension.list.module')->getPath('noahs_page_builder') );

require_once NOAHS_PAGE_BUILDER_PATH . '/includes/control-base.php';

function noahs_page_builder_pro_form_alter(&$form, &$form_state, $form_id) {
  // Verificar si el formulario es el de edición de nodos del tipo 'page'.
  $noahs_page_builder_config = \Drupal::config('noahs_page_builder.settings');

  $route = \Drupal::routeMatch()->getRouteName();
  $route_match = \Drupal::routeMatch();

  $use_in_ctype = $noahs_page_builder_config->get('use_in_ctype');
  $node = $route_match->getParameter('node');

  if($form_id === 'commerce_product_downloads_edit_form'){
    $form['noahs_settings' ] = array(
      '#type' => 'details',
      '#title' => t('Noahs Settings'),
      '#weight' => 1, 
      '#group' => 'advanced',// Puedes ajustar este valor para cambiar la posición del campo.
    );
    $form['noahs_override_default']['#group'] = 'noahs_settings';
    $form['noahs_dontuse']['#group'] = 'noahs_settings';
  }
}


function noahs_page_builder_pro_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  $form['noahs_settings' ] = array(
    '#type' => 'details',
    '#title' => t('Noahs Settings'),
    '#weight' => 1, 
    '#group' => 'advanced',// Puedes ajustar este valor para cambiar la posición del campo.
  );
  $form['noahs_override_default']['#group'] = 'noahs_settings';
  $form['noahs_dontuse']['#group'] = 'noahs_settings';
}

/**
 * Implements hook_entity_base_field_info().
 */
function noahs_page_builder_pro_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {

  if ($entity_type->id() === 'node' || $entity_type->id() === 'commerce_product') {


    $fields['noahs_override_default'] = BaseFieldDefinition::create('boolean')
      ->setLabel( t('Override Default Theme'))
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', array(
        'type'    => 'boolean',
        'weight'  => 1,
      ))
      ->setDisplayConfigurable('form', TRUE);

    $fields['noahs_dontuse'] = BaseFieldDefinition::create('boolean')
      ->setLabel(t('Don`t Use Noahs in this node'))
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', array(
        'type'    => 'boolean',
        'weight'  => 2,
      ))
      ->setDisplayConfigurable('form', TRUE);  

    return $fields;
  }
}


function noahs_page_builder_pro_theme_suggestions_menu_alter(array &$suggestions, array $variables) {
  $route = \Drupal::routeMatch()->getRouteName();

  if($route === 'noahs_page_builder_pro.iframe' || $variables['theme_hook_original'] != 'menu__toolbar__admin'){
 
    $suggestions[] = 'menu__noahs__front';
  }
}


function noahs_page_builder_pro_theme($existing, $type, $theme, $path) {
  return array(
    'noahs-pro-theme-form' => array(
        'variables' => array(
            'type' => '',
            'widgets' => [],
            'page_settings' => [],
        ),
        'path' => $path . '/templates/backend',
    ),
    'noahs-pro-theme-iframe' => array(
        'variables' => array(
            'content' => '',
            'page_settings' => [],
        ),
        'path' => $path . '/templates/backend',
    ),
    'html__preview_theme' => array(
      'template' => 'html--preview--theme-noahs',
      'base hook' => 'html',
      'path' => $path . '/templates/backend',
  ),
    // 'html__admin__structure__noahs_page_builder' => array(
    //   'template' => 'html--theme--noahs',
    //   'base hook' => 'html',
    //   'path' => $path . '/templates/backend',
    // ),
    'page__admin__noahs_page_builder_pro' => array(
      'template' => 'page--noahs-pro-theme-builder',
      'base hook' => 'page',
      'path' => $path . '/templates/backend',
    ),
    'page__preview_theme' => array(
      'template' => 'page--preview--noahs',
      'base hook' => 'page',
      'path' => $path . '/templates/backend',
    ),
    'menu__noahs__front' => array(
      'template' => 'menu--noahs-front',
      'base hook' => 'menu',
      'path' => $path . '/templates/frontend',
    ),
    'input__custom_class' => array(
      'template' => 'input--nohas',
      'path' => $path . '/templates/form',
    ),
    'commerce_product__noahs_teaser' => array(
      'template' => 'commerce-product--noahs-teaser',
      'base hook' => 'commerce_product',
      'path' => $path . '/templates/commerce',
    ),
    'commerce_product__teaser' => array(
      'template' => 'commerce-product--noahs-teaser',
      'base hook' => 'commerce_product',
      'path' => $path . '/templates/commerce',
    ),
    'commerce_cart_block' => array(
      'template' => 'commerce-cart-block',
      'path' => $path . '/templates/commerce',
    ),
  );
}
function noahs_page_builder_pro_preprocess_form_element(&$variables) {

  $config = \Drupal::config('noahs_page_builder.settings');

  $variables['attributes']['class'][] = 'mb-3';
    if($variables['type'] === 'checkbox'){
      if($config->get('checkbox_style')){
        $variables['attributes']['class'][] = 'form-check form-switch';
      }      

    }
}

function noahs_page_builder_pro_preprocess_input(&$variables) {

  if($variables['theme_hook_original'] === 'input__checkbox'){
    $variables['attributes']['class'][] = 'form-check-input';
  }
  
  if($variables['theme_hook_original'] === 'input__textfield'){
    $variables['attributes']['class'][] = 'form-control';
  }
}

function noahs_page_builder_pro_preprocess_textarea(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

function noahs_page_builder_pro_preprocess_select(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

function noahs_page_builder_pro_preprocess_page(&$variables) {

  $route = \Drupal::routeMatch()->getRouteName();
  $route_match = \Drupal::routeMatch();
  $node = $route_match->getParameter('node');

  if($route === 'entity.node.canonical' || $route === 'noahs_page_builder_pro.iframe' || $route === 'entity.commerce_product.canonical'){
      $variables['#attached']['library'][] = 'noahs_page_builder_pro/noahs_page_builder_pro.assets.frontend';
  }
  if($route === 'noahs_page_builder.editor'){
      $variables['#attached']['library'][] = 'noahs_page_builder_pro/noahs_page_builder_pro.assets.editor';
  }
}

function noahs_page_builder_pro_load_widget($wid) {
  $result = \Drupal::database()->select('{noahs_page_builder_pro_global_widget}', 'd')
  ->fields('d')
  ->condition('wid', $wid, '=')
  ->execute()
  ->fetchObject();
return $result;
}

/**
 * Hook hook_some_content_alter().
 */
function noahs_page_builder_pro_default_fileds_alter(&$form) {

  $form['animation_extra'] = [
      'type' => 'group',
      'title' => t('Animation on  Vertical Scroll'),
  ];

  $form['elemenet_animation_active'] = [
      'type'    => 'checkbox',
      'title'   => t('Active'),
      'value' => 'true',
      'default_value' => 'false',
      'tab' => 'section_extras',
      'group' => 'animation_extra'
  ];

  $form['element_animation'] = [
      'type'            => 'select',
      'title'           => ('When'),
      'options'         => [
          ''            => 'Select',
          'view'       => 'View',
          'exit'        => 'Exit',
          'span'        => 'Span',
      ],  
      'style_type'      => 'attribute',
      'style_selector'  => '.widget-wrapper',
      'attribute_type'  => 'data-when',
      'tab'             => 'section_extras',
      'group'           => 'animation_extra',
  ];

  $form['element_animation_transition'] = [
      'type'            => 'select',
      'title'           => ('Transition'),
      'options'         => [
          ''            => 'Select',
          'easeout'       => 'Ease out',
          'easein'        => 'Ease in',
          'easeinout'        => 'Ease in out',
          'linear'        => 'Linear',
      ],  
      'style_type'      => 'attribute',
      'style_selector'  => '.widget-wrapper',
      'attribute_type'  => 'data-easing',
      'tab'             => 'section_extras',
      'group'           => 'animation_extra',
  ];
  

  $form['element_animation_from'] = [
      'type'    => 'number',
      'title'   => ('From'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-from', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
          'max' => '1',
          'step' => '0.01'
       ],
  ];

  $form['element_animation_to'] = [
      'type'    => 'number',
      'title'   => ('To'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-to', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
          'step' => '0.01',
          'max' => '1',
       ],
  ];
  $form['element_animation_opacity'] = [
      'type'    => 'number',
      'title'   => ('Opacity'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-opacity', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
          'max' => '1',
          'step' => '0.01'
       ],
  ];

  $form['element_animation_translatex'] = [
      'type'    => 'number',
      'title'   => ('Horizontal distance'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-translatex', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_translatey'] = [
      'type'    => 'number',
      'title'   => ('Vertical distance'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-translatey', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_translatez'] = [
      'type'    => 'number',
      'title'   => ('Vertical Z'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-translatez', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_rotatex'] = [
      'type'    => 'number',
      'title'   => ('Rotate X'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-rotatex', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_rotatey'] = [
      'type'    => 'number',
      'title'   => ('Rotate Y'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-rotatey', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_rotatez'] = [
      'type'    => 'number',
      'title'   => ('Rotate Z'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-rotatez', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
          'min' => '0',
       ],
  ];
  $form['element_animation_scale'] = [
      'type'    => 'number',
      'title'   => ('Scale'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-scale', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
        'min' => '0',
        'step' => '0.1'
     ],
  ];
  $form['element_animation_scalex'] = [
      'type'    => 'number',
      'title'   => ('Scale X'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-scalex', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
        'min' => '0',
        'step' => '0.1'
     ],
  ];
  $form['element_animation_scaley'] = [
      'type'    => 'number',
      'title'   => ('Scale Y'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-scaley', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
        'min' => '0',
        'step' => '0.1'
     ],
  ];
  $form['element_animation_scalez'] = [
      'type'    => 'number',
      'title'   => ('Scale Z'),
      'style_selector' => '.widget-wrapper', 
      'style_type' => 'attribute',
      'attribute_type' => 'data-scalez', 
      'tab' => 'section_extras',
      'group' => 'animation_extra',
      'attributes' => [
        'min' => '0',
        'step' => '0.1'
     ],
  ];

}